version: 0.2

#phases:
pre_build:
  commands:
    - echo "Cleaning up workspace for a fresh build..."
    - rm -rf build
    - rm -rf .gradle
    - echo "Workspace cleaned."
    - echo "Logging in to Amazon ECR..."
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 034362059976.dkr.ecr.ap-south-1.amazonaws.com

build:
  commands:
    - echo "Starting gradle clean build..."
    - ./gradlew clean build
    - echo "Gradle build finished successfully!"
    - echo "Building the Docker image..."
    - docker build -t product-service:latest .
    - echo "Tagging the Docker image..."
    - docker tag product-service:latest 034362059976.dkr.ecr.ap-south-1.amazonaws.com/product-service:latest

post_build:
  commands:
    - echo "Pushing the Docker image to Amazon ECR..."
    - docker push 034362059976.dkr.ecr.ap-south-1.amazonaws.com/product-service:latest
    - echo "Updating ECS service with the new image..."
    - aws ecs update-service --cluster product-service-cluster --service product-service-service --force-new-deployment --region ap-south-1
    - echo "Creating imagedefinitions.json file..."
    - printf '[{"name":"product-service","imageUri":"034362059976.dkr.ecr.ap-south-1.amazonaws.com/product-service:latest"}]' > imagedefinitions.json
    - echo "imagedefinitions.json file created successfully!"
    - echo "Checking if imagedefinitions.json exists:"
    - cat imagedefinitions.json
    - echo "Listing all files in current directory:"
    - ls -al

artifacts:
  files:
    - imagedefinitions.json
